---
version: '3'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
    container_name: elasticsearch
    environment:
      - cluster.name=microservice-monitoring
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - xpack.security.enabled=$ELASTIC_SECURITY
      - xpack.monitoring.collection.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    networks: ['stack']

  kibana:
    image: docker.elastic.co/kibana/kibana:$ELASTIC_VERSION
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
    container_name: kibana
    volumes:
      - ./scripts:/mnt/scripts:ro
    command: sh -c '/mnt/scripts/wait-for $DEBUG_WAIT_FOR http://elastic:$ELASTIC_PASSWORD@elasticsearch:9200 && /mnt/scripts/kibana.sh'
    ports: ['127.0.0.1:5601:5601']
    networks: ['stack']
    depends_on: ['elasticsearch']

  filebeat:
    image: docker.elastic.co/beats/filebeat:$ELASTIC_VERSION
    user: root
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
    container_name: filebeat
    # If the host system has logs at "/var/log", mount them at "/mnt/log"
    # inside the container, where Filebeat can find them.
    volumes:
      - ./scripts:/mnt/scripts:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/log:/mnt/log:ro
      - $PWD/../java/backend:/mnt/backend-log:ro
      - $PWD/../java/frontend:/mnt/frontend-log:ro
      # Provide a custom Filebeat configuration
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml
    command: sh -c '/mnt/scripts/wait-for $DEBUG_WAIT_FOR http://elastic:$ELASTIC_PASSWORD@kibana:5601/api/status && filebeat -e'
    networks: ['stack']
    depends_on: ['kibana']

  heartbeat:
    image: docker.elastic.co/beats/heartbeat:$ELASTIC_VERSION
    user: root
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
      - KIBANA_HOSTS=http://kibana:5601
    container_name: heartbeat
    volumes:
      - ./scripts:/mnt/scripts:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Provide a custom Heartbeat configuration
      - ./config/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml
    command: sh -c '/mnt/scripts/wait-for $DEBUG_WAIT_FOR http://elastic:$ELASTIC_PASSWORD@kibana:5601/api/status && heartbeat -e'
    networks: ['stack']
    depends_on: ['kibana']

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:$ELASTIC_VERSION
    user: root
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
    container_name: metricbeat
    networks: ['stack']
    # The commented sections below enable Metricbeat to monitor the Docker host,
    # rather than the Metricbeat container. It's problematic with Docker for
    # Windows, however, since "/proc", "/sys", etc. don't exist on Windows.
    volumes:
      - ./scripts:/mnt/scripts:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
      # Provide a custom Metricbeat configuration
      - ./config/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
    command: sh -c '/mnt/scripts/wait-for $DEBUG_WAIT_FOR http://elastic:$ELASTIC_PASSWORD@kibana:5601/api/status && metricbeat -e'
    networks: ['stack']
    depends_on: ['kibana']

  packetbeat:
    image: docker.elastic.co/beats/packetbeat:$ELASTIC_VERSION
    user: root
    environment:
      # Since we did that, Packetbeat is not part of the "stack" Docker network
      # that the other containers are connected to, and thus can't resolve the
      # hostname "elasticsearch". Instead, we'll tell it to find Elasticsearch
      # on "localhost", which is the Docker host machine in this context.
      - ELASTICSEARCH_HOSTS=localhost:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
      - KIBANA_HOSTS=localhost:5601
    container_name: packetbeat
    volumes:
      - ./scripts:/mnt/scripts:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # Provide a custom Packetbeat configuration
      - ./config/packetbeat.yml:/usr/share/packetbeat/packetbeat.yml
    # Packetbeat needs some elevated privileges capture network traffic.
    # We'll grant them with POSIX capabilities.
    cap_add: ['NET_RAW', 'NET_ADMIN']
    # Use "host mode" networking to allow Packetbeat to capture traffic from
    # real network interface on the host, rather than being isolated to the
    # container's virtual interface.
    command: sh -c '/mnt/scripts/wait-for $DEBUG_WAIT_FOR http://elastic:$ELASTIC_PASSWORD@localhost:5601/api/status && packetbeat -e'
    network_mode: host
    depends_on: ['kibana']

  apm-server:
    image: docker.elastic.co/apm/apm-server:$ELASTIC_VERSION
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
    container_name: apm-server
    volumes:
      - ./scripts:/mnt/scripts:ro
      - ./config/apm-server.yml:/usr/share/apm-server/apm-server.yml
    command: sh -c '/mnt/scripts/wait-for $DEBUG_WAIT_FOR http://elastic:$ELASTIC_PASSWORD@elasticsearch:9200 && /mnt/scripts/apm.sh'
    ports: ['127.0.0.1:8200:8200']
    networks: ['stack']
    depends_on: ['elasticsearch']

#volumes:
#  esdata:
#    driver: local


networks:
  stack: {}
