heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls:
    - ${ELASTICSEARCH_HOSTS:elasticsearch:9200}
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'

- type: http
  schedule: '@every 5s'
  urls:
    - ${KIBANA_HOSTS:kibana:5601}

- type: icmp
  schedule: '@every 5s'
  hosts:
    - elasticsearch
    - kibana

processors:
- add_cloud_metadata: ~
- add_docker_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
  username: '${ELASTICSEARCH_USERNAME:}'
  password: '${ELASTICSEARCH_PASSWORD:}'

xpack.monitoring.enabled: true

#setup.kibana:
#  host: "${KIBANA_HOSTS:kibana:5601}"
#  username: '${ELASTICSEARCH_USERNAME:}'
#  password: '${ELASTICSEARCH_PASSWORD:}'
#setup.dashboards.enabled: true
#setup.dashboards.retry.enabled: true
#setup.dashboards.retry.interval: 5s
